// <auto-generated />
using E_Kitabxana.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Kitabxana.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260731113740_AddCartsTable")]
    partial class AddCartsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Kitabxana.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Sənədli-bədii tarixi roman Azərbaycan nəşri üçün yenidən işlənib.",
                            Author = " Mehmet Necati Dəmircan",
                            CategoryId = 0,
                            ImageUrl = "https://static.insales-cdn.com/images/products/1/800/833495840/ELCIBEY_qapaq__1_.jpg",
                            IsDeleted = false,
                            Price = 11.82m,
                            Stock = 0,
                            Title = "Elçibəy"
                        },
                        new
                        {
                            Id = 2,
                            About = "\"Hamilə qız\" povestində sevgi və mənəviyyat xətti işlənib.",
                            Author = "Aləm Kəngərli",
                            CategoryId = 0,
                            ImageUrl = "https://static.insales-cdn.com/r/3WeQLHOLHXk/rs:fit:570:570:1/q:80/plain/images/products/1/2841/2848353049/2025-11-24-11-46-251763970385.jpg@webp",
                            IsDeleted = false,
                            Price = 4.25m,
                            Stock = 0,
                            Title = "Hamilə qız"
                        },
                        new
                        {
                            Id = 3,
                            About = "Bu roman sevginin xilas yox, hökmə çevrildiyi bir dünyada vicdan, sədaqət və günah arasında parçalanan insanların hekayəsidir.",
                            Author = "Nəzakət Cavadova",
                            CategoryId = 0,
                            ImageUrl = "https://static.insales-cdn.com/images/products/1/7401/2848292073/2026-03-09-16-16-221773058582.png",
                            IsDeleted = false,
                            Price = 13.60m,
                            Stock = 0,
                            Title = "13-cü Kottecin Sirri"
                        },
                        new
                        {
                            Id = 4,
                            About = "Fəlsəfə tarixinin məşhur filosofları otağımda peyda oldular.",
                            Author = "Ömər Sevinçgül",
                            CategoryId = 0,
                            ImageUrl = "https://static.insales-cdn.com/images/products/1/673/2848072353/ANI_YASHA_qapaq.jpg",
                            IsDeleted = false,
                            Price = 8.45m,
                            Stock = 0,
                            Title = "Əyləncəli fəlsəfə"
                        },
                        new
                        {
                            Id = 5,
                            About = "Öz həyatını mənalandırmağı və onu gündəlik həyatda tapmağı bacaran insan xoşbəxtdir.",
                            Author = "Bettina Lemke",
                            CategoryId = 0,
                            ImageUrl = "https://static.insales-cdn.com/images/products/1/6425/2926074137/IKIGAI_qapaq.jpg",
                            IsDeleted = false,
                            Price = 8.49m,
                            Stock = 0,
                            Title = "İkigai"
                        },
                        new
                        {
                            Id = 6,
                            About = "Pul məsələsini daha yaxşı öyrədən hekayələr toplusudur.",
                            Author = "Morqan Haruzel",
                            CategoryId = 0,
                            ImageUrl = "https://static.insales-cdn.com/images/products/1/3457/2926046593/PULUN_PSIXOLOGIYASI_qapaq.jpg",
                            IsDeleted = false,
                            Price = 10.19m,
                            Stock = 0,
                            Title = "Pulun Psixologiyası"
                        },
                        new
                        {
                            Id = 7,
                            About = "Cəmiyyətin dərin təzadlarını əks etdirən detektiv janrda yazılan bestsellər.",
                            Author = "Sabir Şahtaxtı",
                            CategoryId = 0,
                            ImageUrl = "https://static.insales-cdn.com/images/products/1/4465/2908098929/2026-03-09-15-15-201773054920.png",
                            IsDeleted = false,
                            Price = 10.12m,
                            Stock = 0,
                            Title = "Mafiya şahid saxlamır"
                        },
                        new
                        {
                            Id = 8,
                            About = "Bəzən həyat səssiz görünür. Sanki hər şey axır, amma heç nə dəyişmir.",
                            Author = "Qurban Səid",
                            CategoryId = 0,
                            ImageUrl = "https://static.insales-cdn.com/images/products/1/5401/2851656985/WhatsApp_Image_2026-03-17_at_10.36.11.jpeg",
                            IsDeleted = false,
                            Price = 10.63m,
                            Stock = 0,
                            Title = "Həmin o an"
                        },
                        new
                        {
                            Id = 9,
                            About = "Ключевые понятия космологии описаны доступным языком.",
                            Author = "Мартин Рис",
                            CategoryId = 0,
                            ImageUrl = "https://static.insales-cdn.com/images/products/1/2585/2855471641/7135681377-large.webp",
                            IsDeleted = false,
                            Price = 11.34m,
                            Stock = 0,
                            Title = "Всего шесть чисел"
                        },
                        new
                        {
                            Id = 10,
                            About = "За многие годы исследований были обнаружены удивительные свидетельства о происхождении Земли.",
                            Author = "Захария Ситчин",
                            CategoryId = 0,
                            ImageUrl = "https://static.insales-cdn.com/images/products/1/1977/2855471033/7328593592.webp",
                            IsDeleted = false,
                            Price = 11.34m,
                            Stock = 0,
                            Title = "Двенадцатая планета"
                        },
                        new
                        {
                            Id = 11,
                            About = "Hadisələr Birinci Dünya müharibəsindən sonrakı Almaniyada cərəyan edir.",
                            Author = "Erix Mariya Remark",
                            CategoryId = 0,
                            ImageUrl = "https://static.insales-cdn.com/images/products/1/265/2904301833/UC_YOLDASH_qapaq.jpg",
                            IsDeleted = false,
                            Price = 11.04m,
                            Stock = 0,
                            Title = "Üç yoldaş"
                        });
                });

            modelBuilder.Entity("E_Kitabxana.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("E_Kitabxana.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tarix"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Roman"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Psixologiya"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fəlsəfə"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Elm"
                        });
                });

            modelBuilder.Entity("E_Kitabxana.Models.Book", b =>
                {
                    b.HasOne("E_Kitabxana.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("E_Kitabxana.Models.Cart", b =>
                {
                    b.HasOne("E_Kitabxana.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("E_Kitabxana.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
